// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdXH3-6oTXv1ms727KbRb79AxNq3991Ik',
    appId: '1:740302132438:web:57adb05bb51768002b2577',
    messagingSenderId: '740302132438',
    projectId: 'novaexpress-f6c0e',
    authDomain: 'novaexpress-f6c0e.firebaseapp.com',
    storageBucket: 'novaexpress-f6c0e.firebasestorage.app',
    measurementId: 'G-7TVR1F43JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtS0m8qIe5XAIlbNfFph_SuVfXSHld7Y',
    appId: '1:740302132438:android:c796767fc084f6ee2b2577',
    messagingSenderId: '740302132438',
    projectId: 'novaexpress-f6c0e',
    storageBucket: 'novaexpress-f6c0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2V8rGhQgMZtM4WLeqGaFQbl_1_p4U8ho',
    appId: '1:740302132438:ios:3f4ab73b012833352b2577',
    messagingSenderId: '740302132438',
    projectId: 'novaexpress-f6c0e',
    storageBucket: 'novaexpress-f6c0e.firebasestorage.app',
    iosBundleId: 'com.example.novaexpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2V8rGhQgMZtM4WLeqGaFQbl_1_p4U8ho',
    appId: '1:740302132438:ios:3f4ab73b012833352b2577',
    messagingSenderId: '740302132438',
    projectId: 'novaexpress-f6c0e',
    storageBucket: 'novaexpress-f6c0e.firebasestorage.app',
    iosBundleId: 'com.example.novaexpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdXH3-6oTXv1ms727KbRb79AxNq3991Ik',
    appId: '1:740302132438:web:3dadf1223f6ceced2b2577',
    messagingSenderId: '740302132438',
    projectId: 'novaexpress-f6c0e',
    authDomain: 'novaexpress-f6c0e.firebaseapp.com',
    storageBucket: 'novaexpress-f6c0e.firebasestorage.app',
    measurementId: 'G-WF3N2RQRNG',
  );
}
